--------------------------------------------------
-- LIMPIEZA
--------------------------------------------------
DROP TABLE PASAJES CASCADE CONSTRAINTS;
DROP TABLE TIPOS_PASAJE CASCADE CONSTRAINTS;
DROP TABLE UNIDADES CASCADE CONSTRAINTS;
DROP TABLE RUTAS CASCADE CONSTRAINTS;

--------------------------------------------------
-- 1. RUTAS
--------------------------------------------------
CREATE TABLE RUTAS (
    codigo        VARCHAR2(10) PRIMARY KEY,
    origen        VARCHAR2(100) NOT NULL,
    destino       VARCHAR2(100) NOT NULL,
    precio_base   NUMBER(10,2) NOT NULL CHECK (precio_base > 0),
    is_deleted    CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT ck_rutas_deleted CHECK (is_deleted IN ('S','N'))
);

--------------------------------------------------
-- 2. UNIDADES
--------------------------------------------------
CREATE TABLE UNIDADES (
    codigo      VARCHAR2(10) PRIMARY KEY,
    placa       VARCHAR2(10) UNIQUE NOT NULL,
    capacidad   NUMBER(3) NOT NULL CHECK (capacidad > 0),
    is_deleted  CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT ck_unidades_deleted CHECK (is_deleted IN ('S','N'))
);

--------------------------------------------------
-- 3. TIPOS DE PASAJE
--------------------------------------------------
CREATE TABLE TIPOS_PASAJE (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion         VARCHAR2(50) NOT NULL,
    descuento_decimal   NUMBER(5,4) NOT NULL CHECK (descuento_decimal BETWEEN 0 AND 1),
    is_deleted          CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT ck_tipos_deleted CHECK (is_deleted IN ('S','N'))
);

--------------------------------------------------
-- 4. PASAJES
--------------------------------------------------
CREATE TABLE PASAJES (
    id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unidad_id         VARCHAR2(10) NOT NULL,
    ruta_id           VARCHAR2(10) NOT NULL,
    tipo_pasaje_id    NUMBER NOT NULL,
    valor_base        NUMBER(10,2),
    valor_descuento   NUMBER(10,2),
    valor_final       NUMBER(10,2),
    fecha_hora        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted        CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT ck_pasajes_deleted CHECK (is_deleted IN ('S','N')),
    CONSTRAINT fk_unidad FOREIGN KEY (unidad_id) REFERENCES UNIDADES(codigo),
    CONSTRAINT fk_ruta FOREIGN KEY (ruta_id) REFERENCES RUTAS(codigo),
    CONSTRAINT fk_tipo FOREIGN KEY (tipo_pasaje_id) REFERENCES TIPOS_PASAJE(id)
);

--------------------------------------------------
-- DATOS INICIALES
--------------------------------------------------
INSERT INTO TIPOS_PASAJE (descripcion, descuento_decimal) VALUES ('Normal', 0.00);
INSERT INTO TIPOS_PASAJE (descripcion, descuento_decimal) VALUES ('Tercera Edad', 0.60);
INSERT INTO TIPOS_PASAJE (descripcion, descuento_decimal) VALUES ('Estudiante', 0.40);
INSERT INTO TIPOS_PASAJE (descripcion, descuento_decimal) VALUES ('Discapacidad', 0.50);

INSERT INTO RUTAS (codigo, origen, destino, precio_base)
VALUES ('UIO-GUA', 'Quito', 'Guayaquil', 12.00);

INSERT INTO RUTAS (codigo, origen, destino, precio_base)
VALUES ('IBA-UIO', 'Ibarra', 'Quito', 3.50);

INSERT INTO RUTAS (codigo, origen, destino, precio_base)
VALUES ('CUE-GUA', 'Cuenca', 'Guayaquil', 8.50);

INSERT INTO UNIDADES (codigo, placa, capacidad)
VALUES ('B-001', 'IAA-1234', 45);

INSERT INTO UNIDADES (codigo, placa, capacidad)
VALUES ('B-002', 'PBA-5678', 42);

INSERT INTO UNIDADES (codigo, placa, capacidad)
VALUES ('B-003', 'GBC-9012', 40);

COMMIT;

--------------------------------------------------
-- TRIGGER: CALCULAR VALORES DEL PASAJE
--------------------------------------------------
CREATE OR REPLACE TRIGGER TRG_CALCULAR_PRECIO_PASAJE
BEFORE INSERT ON PASAJES
FOR EACH ROW
DECLARE
    v_descuento NUMBER;
    v_precio    NUMBER;
BEGIN
    SELECT descuento_decimal
    INTO v_descuento
    FROM TIPOS_PASAJE
    WHERE id = :NEW.tipo_pasaje_id
      AND is_deleted = 'N';

    SELECT precio_base
    INTO v_precio
    FROM RUTAS
    WHERE codigo = :NEW.ruta_id
      AND is_deleted = 'N';

    :NEW.valor_base      := v_precio;
    :NEW.valor_descuento := v_precio * v_descuento;
    :NEW.valor_final     := v_precio - :NEW.valor_descuento;
END;
/

--------------------------------------------------
-- FUNCIÓN: EXPORTAR PASAJES COMO CSV (CLOB)
--------------------------------------------------
CREATE OR REPLACE FUNCTION GET_PASAJES_CSV (
    p_ruta_codigo   IN VARCHAR2 DEFAULT NULL,
    p_fecha_inicio  IN DATE     DEFAULT NULL,
    p_fecha_fin     IN DATE     DEFAULT NULL
)
RETURN CLOB
IS
    v_csv   CLOB;

    CURSOR c_pasajes IS
        SELECT 
            p.id,
            TO_CHAR(p.fecha_hora, 'YYYY-MM-DD HH24:MI:SS') fecha,
            u.placa,
            ru.origen || '-' || ru.destino ruta,
            p.valor_base,
            p.valor_descuento,
            tp.descripcion,
            p.valor_final
        FROM PASAJES p
        JOIN UNIDADES u 
            ON p.unidad_id = u.codigo
           AND u.is_deleted = 'N'
        JOIN RUTAS ru 
            ON p.ruta_id = ru.codigo
           AND ru.is_deleted = 'N'
        JOIN TIPOS_PASAJE tp 
            ON p.tipo_pasaje_id = tp.id
           AND tp.is_deleted = 'N'
        WHERE p.is_deleted = 'N'
          AND (p_ruta_codigo IS NULL OR p.ruta_id = p_ruta_codigo)
          AND (p_fecha_inicio IS NULL OR p.fecha_hora >= p_fecha_inicio)
          AND (p_fecha_fin IS NULL OR p.fecha_hora <= p_fecha_fin)
        ORDER BY p.fecha_hora;

    v_row c_pasajes%ROWTYPE;

BEGIN
    v_csv := 'ID,FECHA,PLACA,RUTA,BASE,DESCUENTO,TIPO,FINAL' || CHR(10);

    OPEN c_pasajes;
    LOOP
        FETCH c_pasajes INTO v_row;
        EXIT WHEN c_pasajes%NOTFOUND;

        v_csv := v_csv ||
                 v_row.id || ',' ||
                 v_row.fecha || ',' ||
                 v_row.placa || ',' ||
                 v_row.ruta || ',' ||
                 v_row.valor_base || ',' ||
                 v_row.valor_descuento || ',' ||
                 v_row.descripcion || ',' ||
                 v_row.valor_final || CHR(10);
    END LOOP;
    CLOSE c_pasajes;

    RETURN v_csv;
END;
/
